import Navbar1 from "../Sections/Generic/Navbars/Navbar1";
import Navbar2 from "../Sections/Generic/Navbars/Navbar2";
import Navbar3 from "../Sections/Generic/Navbars/Navbar3";
import Hero1 from "../Sections/Generic/Heros/Hero1";
import Hero2 from "../Sections/Generic/Heros/Hero2";
import Hero3 from "../Sections/Generic/Heros/Hero3";
import Features1 from "../Sections/Generic/Features/Features1";
import Features2 from "../Sections/Generic/Features/Features2";
import Features3 from "../Sections/Generic/Features/Features3";
import Pricing1 from "../Sections/Generic/Pricing/Pricing1";
import Pricing2 from "../Sections/Generic/Pricing/Pricing2";
import Pricing3 from "../Sections/Generic/Pricing/Pricing3";
import WorkPage1 from "../Sections/Generic/Pages/WorkPage1";
import WorkPage2 from "../Sections/Generic/Pages/WorkPage2";
import WorkPage3 from "../Sections/Generic/Pages/WorkPage3";
import WorkPage4 from "../Sections/Generic/Pages/WorkPage4";
import Footer1 from "../Sections/Generic/Footers/Footer1";
import Footer2 from "../Sections/Generic/Footers/Footer2";
import Footer3 from "../Sections/Generic/Footers/Footer3";

// Portfolio Components
import PortfolioNavbar1 from "../Sections/Portfolio/Navbar/Navbar1";
import PortfolioNavbar2 from "../Sections/Portfolio/Navbar/Navbar2";
import PortfolioNavbar3 from "../Sections/Portfolio/Navbar/Navbar3";
import PortfolioHero1 from "../Sections/Portfolio/Hero/Hero1";
import PortfolioHero2 from "../Sections/Portfolio/Hero/Hero2";
import PortfolioHero3 from "../Sections/Portfolio/Hero/Hero3";
import PortfolioProjects1 from "../Sections/Portfolio/Projects/Projects1";
import PortfolioProjects2 from "../Sections/Portfolio/Projects/Projects2";
import PortfolioProjects3 from "../Sections/Portfolio/Projects/Projects3";
import PortfolioSkills1 from "../Sections/Portfolio/Skills/Skills1";
import PortfolioSkills2 from "../Sections/Portfolio/Skills/Skills2";
import PortfolioSkills3 from "../Sections/Portfolio/Skills/Skills3";
import PortfolioFooter1 from "../Sections/Portfolio/Footer/Footer1";
import PortfolioFooter2 from "../Sections/Portfolio/Footer/Footer2";
import PortfolioFooter3 from "../Sections/Portfolio/Footer/Footer3";
import PortfolioTemplate1 from "../Sections/Portfolio/Pages/PortfolioTemplate1";
import PortfolioTemplate2 from "../Sections/Portfolio/Pages/PortfolioTemplate2";
import PortfolioTemplate3 from "../Sections/Portfolio/Pages/PortfolioTemplate3";
import PortfolioTemplate4 from "../Sections/Portfolio/Pages/PortfolioTemplate4";

const sectionRegistry = [
    {
        id: "navbar1",
        title: "Navbar 1",
        group: "navbar",
        Component: Navbar1,
        defaultContent: {
            brand: "YourBrand",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Contact",
            cta: "Get Started",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "navbar2",
        title: "Navbar 2",
        group: "navbar",
        Component: Navbar2,
        defaultContent: {
            brand: "YourBrand",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Contact",
            cta: "Get Started",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "navbar3",
        title: "Navbar 3",
        group: "navbar",
        Component: Navbar3,
        defaultContent: {
            brand: "YourBrand",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Contact",
            cta: "Get Started",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "hero1",
        title: "Hero 1",
        group: "hero",
        Component: Hero1,
        defaultContent: {
            badge: "> YOUR HEADLINE",
            title: "Welcome to Your Template",
            description: "Craft the perfect landing page for your brand with our drag-and-drop template builder.",
            buttonLabel: "Get Started",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "hero2",
        title: "Hero 2",
        group: "hero",
        Component: Hero2,
        defaultContent: {
            badge: "> YOUR TAGLINE",
            title: "Create Amazing Experiences",
            description: "Build a professional website using our flexible templates and components.",
            buttonLabel: "Learn More",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "hero3",
        title: "Hero 3",
        group: "hero",
        Component: Hero3,
        defaultContent: {
            badge: "> ACCELERATE GROWTH",
            title: "Launch Your Vision",
            description: "Transform your ideas into reality with our intuitive webpage template builder.",
            buttonLabel: "Start Building",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "features1",
        title: "Features 1",
        group: "features",
        Component: Features1,
        defaultContent: {
            badge: "> WHY CHOOSE US",
            title: "Powerful Features Built In",
            feature1Title: "Easy to Use",
            feature1Desc: "Intuitive interface that requires no coding knowledge.",
            feature2Title: "Fully Customizable",
            feature2Desc: "Customize colors, fonts, and layouts to match your brand.",
            feature3Title: "Mobile Responsive",
            feature3Desc: "Your template looks perfect on all devices automatically.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "features2",
        title: "Features 2",
        group: "features",
        Component: Features2,
        defaultContent: {
            badge: "> KEY BENEFITS",
            title: "Everything You Need",
            feature1Title: "Lightning Fast",
            feature1Desc: "Deploy your website in seconds with optimized templates.",
            feature2Title: "SEO Optimized",
            feature2Desc: "Built-in SEO best practices help you rank higher.",
            feature3Title: "Conversion Focused",
            feature3Desc: "Strategically designed layouts to maximize conversions.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "features3",
        title: "Features 3",
        group: "features",
        Component: Features3,
        defaultContent: {
            badge: "> GO FURTHER",
            title: "Advanced Capabilities",
            feature1Title: "Analytics Ready",
            feature1Desc: "Track visitor behavior with integrated analytics tools.",
            feature2Title: "Email Marketing",
            feature2Desc: "Connect with your favorite email marketing platforms.",
            feature3Title: "API Integration",
            feature3Desc: "Extend functionality with powerful API capabilities.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "pricing1",
        title: "Pricing 1",
        group: "pricing",
        Component: Pricing1,
        defaultContent: {
            badge: "> TRANSPARENT PRICING",
            title: "Choose Your Plan",
            plan1Name: "Starter",
            plan1Price: "$9",
            plan1Desc: "Perfect for getting started with essential features.",
            plan2Name: "Professional",
            plan2Price: "$29",
            plan2Desc: "Everything you need to grow your business.",
            plan3Name: "Enterprise",
            plan3Price: "$99",
            plan3Desc: "Advanced features and dedicated support.",
            buttonLabel: "Select Plan",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "pricing2",
        title: "Pricing 2",
        group: "pricing",
        Component: Pricing2,
        defaultContent: {
            badge: "> PRICING PLANS",
            title: "Simple & Fair Pricing",
            plan1Name: "Starter",
            plan1Price: "$9",
            plan1Desc: "Perfect for getting started with essential features.",
            plan2Name: "Professional",
            plan2Price: "$29",
            plan2Desc: "Everything you need to grow your business.",
            plan3Name: "Enterprise",
            plan3Price: "$99",
            plan3Desc: "Advanced features and dedicated support.",
            buttonLabel: "Get Started",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "pricing3",
        title: "Pricing 3",
        group: "pricing",
        Component: Pricing3,
        defaultContent: {
            badge: "> FIND YOUR FIT",
            title: "Affordable Plans for Everyone",
            plan1Name: "Starter",
            plan1Price: "$9",
            plan1Desc: "Perfect for getting started with essential features.",
            plan2Name: "Professional",
            plan2Price: "$29",
            plan2Desc: "Everything you need to grow your business.",
            plan3Name: "Enterprise",
            plan3Price: "$99",
            plan3Desc: "Advanced features and dedicated support.",
            buttonLabel: "Choose Plan",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "workpage1",
        title: "WorkPage 1",
        group: "work",
        Component: WorkPage1,
        defaultContent: {
            badge: "> OUR PROCESS",
            title: "How It Works",
            description:
                "We make it simple to create stunning websites. Follow our straightforward process to get your template ready in minutes.",
            item1: "Choose Your Template",
            item2: "Customize Your Content",
            item3: "Design Your Look",
            item4: "Download & Deploy",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage2",
        title: "WorkPage 2",
        group: "work",
        Component: WorkPage2,
        defaultContent: {
            badge: "> GETTING STARTED",
            title: "Step-by-Step Guide",
            description:
                "Jumpstart your website with our comprehensive guide. Everything you need to know to succeed.",
            item1: "Select & Customize",
            item2: "Edit Content",
            item3: "Apply Branding",
            item4: "Export & Publish",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage3",
        title: "WorkPage 3",
        group: "work",
        Component: WorkPage3,
        defaultContent: {
            badge: "> SUCCESS STORIES",
            title: "What You Can Build",
            description:
                "Create professional websites in minutes with our flexible and powerful template system.",
            item1: "Marketing Websites",
            item2: "Product Launches",
            item3: "SaaS Landing Pages",
            item4: "Service Portfolios",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage4",
        title: "WorkPage 4",
        group: "work",
        Component: WorkPage4,
        defaultContent: {
            badge: "> READY TO LAUNCH",
            title: "Export Your Project Code",
            description:
                "Download your exact generated React page code with all selected sections and content already wired.",
            item1: "GeneratedTemplate.jsx",
            item2: "All Selected Sections",
            item3: "Your Edited Content",
            item4: "Ready To Drop Into Project",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "footer1",
        title: "Footer 1",
        group: "footer",
        Component: Footer1,
        defaultContent: {
            brand: "YourBrand",
            subtitle: "Professional Templates Made Simple",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Support",
            copyrightLine: "© 2024 YourBrand. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
    {
        id: "footer2",
        title: "Footer 2",
        group: "footer",
        Component: Footer2,
        defaultContent: {
            brand: "YourBrand",
            subtitle: "Professional Templates Made Simple",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Support",
            copyrightLine: "© 2024 YourBrand. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
    {
        id: "footer3",
        title: "Footer 3",
        group: "footer",
        Component: Footer3,
        defaultContent: {
            brand: "YourBrand",
            subtitle: "Professional Templates Made Simple",
            link1: "Home",
            link2: "Features",
            link3: "Pricing",
            link4: "Support",
            copyrightLine: "© 2024 YourBrand. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
    
    // Portfolio Sections
    {
        id: "portfolio-navbar1",
        title: "Portfolio Navbar 1",
        group: "portfolio-navbar",
        Component: PortfolioNavbar1,
        defaultContent: {
            logo: "JD.",
            link1: "Work",
            link2: "Services",
            link3: "About",
            ctaLabel: "Let's Talk",
            backgroundColor: "#09090b",
            textColor: "#f4f4f5",
            accentColor: "#10b981",
        },
        fields: [
            { key: "logo", label: "Logo" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "ctaLabel", label: "CTA Label" },
        ],
    },
    {
        id: "portfolio-navbar2",
        title: "Portfolio Navbar 2",
        group: "portfolio-navbar",
        Component: PortfolioNavbar2,
        defaultContent: {
            brandName: "Alex",
            tagline: "Developer",
            nav1: "Portfolio",
            nav2: "About",
            nav3: "Blog",
            nav4: "Contact",
            ctaLabel: "Hire Me",
        },
        fields: [
            { key: "brandName", label: "Brand Name" },
            { key: "tagline", label: "Tagline" },
            { key: "nav1", label: "Nav 1" },
            { key: "nav2", label: "Nav 2" },
            { key: "nav3", label: "Nav 3" },
            { key: "nav4", label: "Nav 4" },
            { key: "ctaLabel", label: "CTA Label" },
        ],
    },
    {
        id: "portfolio-navbar3",
        title: "Portfolio Navbar 3",
        group: "portfolio-navbar",
        Component: PortfolioNavbar3,
        defaultContent: {
            logo: "Portfolio",
            link1: "Home",
            link2: "Projects",
            link3: "Experience",
            link4: "Contact",
            resumeLabel: "Resume",
        },
        fields: [
            { key: "logo", label: "Logo" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "resumeLabel", label: "Resume Label" },
        ],
    },
    {
        id: "portfolio-hero1",
        title: "Portfolio Hero 1",
        group: "portfolio-hero",
        Component: PortfolioHero1,
        defaultContent: {
            badge: "🟢 AVAILABLE FOR FREELANCE",
            title: "Creative Developer & UI/UX Designer",
            description: "I bridge the gap between design and engineering to build pixel-perfect, accessible, and interactive digital experiences.",
            buttonLabel: "View Selected Work",
            imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
            { key: "imageUrl", label: "Image URL" },
        ],
    },
    {
        id: "portfolio-hero2",
        title: "Portfolio Hero 2",
        group: "portfolio-hero",
        Component: PortfolioHero2,
        defaultContent: {
            pretitle: "HELLO, I'M",
            name: "Alex Johnson",
            tagline: "Full-Stack Developer & Creative Technologist",
            subtitle: "Crafting digital experiences that matter.",
            cta1Label: "Explore My Work",
            cta2Label: "Let's Talk",
            scrollIndicator: "↓ Scroll to explore",
        },
        fields: [
            { key: "pretitle", label: "Pretitle" },
            { key: "name", label: "Name" },
            { key: "tagline", label: "Tagline" },
            { key: "subtitle", label: "Subtitle", multiline: true },
            { key: "cta1Label", label: "CTA 1 Label" },
            { key: "cta2Label", label: "CTA 2 Label" },
            { key: "scrollIndicator", label: "Scroll Indicator" },
        ],
    },
    {
        id: "portfolio-hero3",
        title: "Portfolio Hero 3",
        group: "portfolio-hero",
        Component: PortfolioHero3,
        defaultContent: {
            headline: "Turning Ideas Into Digital Reality",
            subheadline: "Full-stack developer crafting beautiful, functional web experiences",
            stat1Label: "Projects Completed",
            stat1Value: "50+",
            stat2Label: "Happy Clients",
            stat2Value: "30+",
            stat3Label: "Years Experience",
            stat3Value: "5+",
            primaryButtonLabel: "View Portfolio",
            secondaryButtonLabel: "Download CV",
        },
        fields: [
            { key: "headline", label: "Headline" },
            { key: "subheadline", label: "Subheadline" },
            { key: "stat1Label", label: "Stat 1 Label" },
            { key: "stat1Value", label: "Stat 1 Value" },
            { key: "stat2Label", label: "Stat 2 Label" },
            { key: "stat2Value", label: "Stat 2 Value" },
            { key: "stat3Label", label: "Stat 3 Label" },
            { key: "stat3Value", label: "Stat 3 Value" },
            { key: "primaryButtonLabel", label: "Primary Button" },
            { key: "secondaryButtonLabel", label: "Secondary Button" },
        ],
    },
    {
        id: "portfolio-projects1",
        title: "Portfolio Projects 1",
        group: "portfolio-projects",
        Component: PortfolioProjects1,
        defaultContent: {
            sectionTitle: "Featured Projects",
            sectionSubtitle: "A selection of work I'm proud of",
            project1Title: "E-Commerce Platform",
            project1Description: "Modern shopping experience with real-time inventory",
            project1Tag: "React • Node.js • MongoDB",
            project2Title: "Analytics Dashboard",
            project2Description: "Real-time data visualization and reporting",
            project2Tag: "Vue.js • D3.js • Python",
            project3Title: "Social App",
            project3Description: "Community-driven platform with messaging",
            project3Tag: "React • Firebase • GraphQL",
        },
        fields: [
            { key: "sectionTitle", label: "Section Title" },
            { key: "sectionSubtitle", label: "Section Subtitle" },
            { key: "project1Title", label: "Project 1 Title" },
            { key: "project1Description", label: "Project 1 Description" },
            { key: "project1Tag", label: "Project 1 Tag" },
            { key: "project2Title", label: "Project 2 Title" },
            { key: "project2Description", label: "Project 2 Description" },
            { key: "project2Tag", label: "Project 2 Tag" },
            { key: "project3Title", label: "Project 3 Title" },
            { key: "project3Description", label: "Project 3 Description" },
            { key: "project3Tag", label: "Project 3 Tag" },
        ],
    },
    {
        id: "portfolio-projects2",
        title: "Portfolio Projects 2",
        group: "portfolio-projects",
        Component: PortfolioProjects2,
        defaultContent: {
            heading: "Recent Work",
            subheading: "Showcasing my latest projects and work samples",
            project1Title: "Project One",
            project1Desc: "Description of your project",
            project1Image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=500&q=60",
            project2Title: "Project Two",
            project2Desc: "Description of your project",
            project2Image: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?auto=format&fit=crop&w=500&q=60",
            project3Title: "Project Three",
            project3Desc: "Description of your project",
            project3Image: "https://images.unsplash.com/photo-1460925895917-adf4e0655519?auto=format&fit=crop&w=500&q=60",
            project4Title: "Project Four",
            project4Desc: "Description of your project",
            project4Image: "https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&w=500&q=60",
        },
        fields: [
            { key: "heading", label: "Heading" },
            { key: "subheading", label: "Subheading" },
            { key: "project1Title", label: "Project 1 Title" },
            { key: "project1Desc", label: "Project 1 Description" },
            { key: "project1Image", label: "Project 1 Image URL" },
            { key: "project2Title", label: "Project 2 Title" },
            { key: "project2Desc", label: "Project 2 Description" },
            { key: "project2Image", label: "Project 2 Image URL" },
            { key: "project3Title", label: "Project 3 Title" },
            { key: "project3Desc", label: "Project 3 Description" },
            { key: "project3Image", label: "Project 3 Image URL" },
            { key: "project4Title", label: "Project 4 Title" },
            { key: "project4Desc", label: "Project 4 Description" },
            { key: "project4Image", label: "Project 4 Image URL" },
        ],
    },
    {
        id: "portfolio-projects3",
        title: "Portfolio Projects 3",
        group: "portfolio-projects",
        Component: PortfolioProjects3,
        defaultContent: {
            sectionTitle: "Portfolio",
            sectionDescription: "Explore my recent projects and work samples",
            project1: "Project 1",
            project2: "Project 2",
            project3: "Project 3",
            project4: "Project 4",
            project5: "Project 5",
            project6: "Project 6",
            viewLabel: "View Project",
        },
        fields: [
            { key: "sectionTitle", label: "Section Title" },
            { key: "sectionDescription", label: "Section Description" },
            { key: "project1", label: "Project 1" },
            { key: "project2", label: "Project 2" },
            { key: "project3", label: "Project 3" },
            { key: "project4", label: "Project 4" },
            { key: "project5", label: "Project 5" },
            { key: "project6", label: "Project 6" },
            { key: "viewLabel", label: "View Label" },
        ],
    },
    {
        id: "portfolio-skills1",
        title: "Portfolio Skills 1",
        group: "portfolio-skills",
        Component: PortfolioSkills1,
        defaultContent: {
            title: "Skills & Expertise",
            subtitle: "Technologies and tools I work with",
            skill1: "JavaScript",
            skill2: "React",
            skill3: "TypeScript",
            skill4: "Node.js",
            skill5: "MongoDB",
            skill6: "Tailwind CSS",
            skill7: "GraphQL",
            skill8: "AWS",
        },
        fields: [
            { key: "title", label: "Title" },
            { key: "subtitle", label: "Subtitle" },
            { key: "skill1", label: "Skill 1" },
            { key: "skill2", label: "Skill 2" },
            { key: "skill3", label: "Skill 3" },
            { key: "skill4", label: "Skill 4" },
            { key: "skill5", label: "Skill 5" },
            { key: "skill6", label: "Skill 6" },
            { key: "skill7", label: "Skill 7" },
            { key: "skill8", label: "Skill 8" },
        ],
    },
    {
        id: "portfolio-skills2",
        title: "Portfolio Skills 2",
        group: "portfolio-skills",
        Component: PortfolioSkills2,
        defaultContent: {
            sectionTitle: "Technical Skills",
            frontendTitle: "Frontend",
            frontend1: "HTML5",
            frontend2: "CSS3",
            frontend3: "JavaScript",
            frontend4: "React",
            backendTitle: "Backend",
            backend1: "Node.js",
            backend2: "Python",
            backend3: "SQL",
            backend4: "MongoDB",
            toolsTitle: "Tools & Platforms",
            tools1: "Git",
            tools2: "Docker",
            tools3: "AWS",
            tools4: "Figma",
        },
        fields: [
            { key: "sectionTitle", label: "Section Title" },
            { key: "frontendTitle", label: "Frontend Title" },
            { key: "frontend1", label: "Frontend 1" },
            { key: "frontend2", label: "Frontend 2" },
            { key: "frontend3", label: "Frontend 3" },
            { key: "frontend4", label: "Frontend 4" },
            { key: "backendTitle", label: "Backend Title" },
            { key: "backend1", label: "Backend 1" },
            { key: "backend2", label: "Backend 2" },
            { key: "backend3", label: "Backend 3" },
            { key: "backend4", label: "Backend 4" },
            { key: "toolsTitle", label: "Tools Title" },
            { key: "tools1", label: "Tool 1" },
            { key: "tools2", label: "Tool 2" },
            { key: "tools3", label: "Tool 3" },
            { key: "tools4", label: "Tool 4" },
        ],
    },
    {
        id: "portfolio-skills3",
        title: "Portfolio Skills 3",
        group: "portfolio-skills",
        Component: PortfolioSkills3,
        defaultContent: {
            title: "Core Competencies",
            description: "Areas where I excel and create value",
            competency1: "Web Development",
            competency1Desc: "Full-stack development with modern frameworks and best practices",
            competency2: "UI/UX Design",
            competency2Desc: "Creating beautiful, intuitive, and accessible user interfaces",
            competency3: "Problem Solving",
            competency3Desc: "Analytical approach to complex technical challenges",
            competency4: "Team Collaboration",
            competency4Desc: "Effective communication and agile methodology experience",
        },
        fields: [
            { key: "title", label: "Title" },
            { key: "description", label: "Description" },
            { key: "competency1", label: "Competency 1" },
            { key: "competency1Desc", label: "Competency 1 Description" },
            { key: "competency2", label: "Competency 2" },
            { key: "competency2Desc", label: "Competency 2 Description" },
            { key: "competency3", label: "Competency 3" },
            { key: "competency3Desc", label: "Competency 3 Description" },
            { key: "competency4", label: "Competency 4" },
            { key: "competency4Desc", label: "Competency 4 Description" },
        ],
    },
    {
        id: "portfolio-footer1",
        title: "Portfolio Footer 1",
        group: "portfolio-footer",
        Component: PortfolioFooter1,
        defaultContent: {
            copyright: "© 2025 Your Name. All rights reserved.",
            social1Link: "#",
            social1Label: "LinkedIn",
            social2Link: "#",
            social2Label: "GitHub",
            social3Link: "#",
            social3Label: "Twitter",
            social4Link: "#",
            social4Label: "Email",
        },
        fields: [
            { key: "copyright", label: "Copyright" },
            { key: "social1Label", label: "Social 1" },
            { key: "social2Label", label: "Social 2" },
            { key: "social3Label", label: "Social 3" },
            { key: "social4Label", label: "Social 4" },
        ],
    },
    {
        id: "portfolio-footer2",
        title: "Portfolio Footer 2",
        group: "portfolio-footer",
        Component: PortfolioFooter2,
        defaultContent: {
            sectionTitle: "Let's Connect",
            email: "hello@yourname.com",
            phone: "+1 (555) 123-4567",
            location: "San Francisco, CA",
            footerText: "Open to freelance and full-time opportunities",
        },
        fields: [
            { key: "sectionTitle", label: "Section Title" },
            { key: "email", label: "Email" },
            { key: "phone", label: "Phone" },
            { key: "location", label: "Location" },
            { key: "footerText", label: "Footer Text" },
        ],
    },
    {
        id: "portfolio-footer3",
        title: "Portfolio Footer 3",
        group: "portfolio-footer",
        Component: PortfolioFooter3,
        defaultContent: {
            quote: "Thank you for visiting my portfolio",
            quote2: "Let's create something amazing together",
            ctaLabel: "Start a Project",
            ctaLink: "#contact",
            navLink1: "Home",
            navLink2: "Portfolio",
            navLink3: "Services",
            navLink4: "Contact",
            copyright: "© 2025. All rights reserved.",
        },
        fields: [
            { key: "quote", label: "Quote 1" },
            { key: "quote2", label: "Quote 2" },
            { key: "ctaLabel", label: "CTA Label" },
            { key: "navLink1", label: "Nav Link 1" },
            { key: "navLink2", label: "Nav Link 2" },
            { key: "navLink3", label: "Nav Link 3" },
            { key: "navLink4", label: "Nav Link 4" },
            { key: "copyright", label: "Copyright" },
        ],
    },
    {
        id: "portfolio-template1",
        title: "Portfolio Template 1",
        group: "portfolio-template",
        Component: PortfolioTemplate1,
        defaultContent: {},
        fields: [],
    },
    {
        id: "portfolio-template2",
        title: "Portfolio Template 2",
        group: "portfolio-template",
        Component: PortfolioTemplate2,
        defaultContent: {},
        fields: [],
    },
    {
        id: "portfolio-template3",
        title: "Portfolio Template 3",
        group: "portfolio-template",
        Component: PortfolioTemplate3,
        defaultContent: {},
        fields: [],
    },
    {
        id: "portfolio-template4",
        title: "Portfolio Template 4",
        group: "portfolio-template",
        Component: PortfolioTemplate4,
        defaultContent: {},
        fields: [],
    },
];

export default sectionRegistry;