import Navbar1 from "../Sections/Generic/Navbars/Navbar1";
import Navbar2 from "../Sections/Generic/Navbars/Navbar2";
import Navbar3 from "../Sections/Generic/Navbars/Navbar3";
import Hero1 from "../Sections/Generic/Heros/Hero1";
import Hero2 from "../Sections/Generic/Heros/Hero2";
import Hero3 from "../Sections/Generic/Heros/Hero3";
import Features1 from "../Sections/Generic/Features/Features1";
import Features2 from "../Sections/Generic/Features/Features2";
import Features3 from "../Sections/Generic/Features/Features3";
import Pricing1 from "../Sections/Generic/Pricing/Pricing1";
import Pricing2 from "../Sections/Generic/Pricing/Pricing2";
import Pricing3 from "../Sections/Generic/Pricing/Pricing3";
import WorkPage1 from "../Sections/Generic/Pages/WorkPage1";
import WorkPage2 from "../Sections/Generic/Pages/WorkPage2";
import WorkPage3 from "../Sections/Generic/Pages/WorkPage3";
import WorkPage4 from "../Sections/Generic/Pages/WorkPage4";
import Footer1 from "../Sections/Generic/Footers/Footer1";
import Footer2 from "../Sections/Generic/Footers/Footer2";
import Footer3 from "../Sections/Generic/Footers/Footer3";

const sectionRegistry = [
    {
        id: "navbar1",
        title: "Navbar 1",
        group: "navbar",
        Component: Navbar1,
        defaultContent: {
            brand: "BLCKS",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            cta: "Login",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "navbar2",
        title: "Navbar 2",
        group: "navbar",
        Component: Navbar2,
        defaultContent: {
            brand: "BLCKS",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            cta: "Start",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "navbar3",
        title: "Navbar 3",
        group: "navbar",
        Component: Navbar3,
        defaultContent: {
            brand: "BLCKS",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            cta: "Login",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "cta", label: "CTA Button" },
        ],
    },
    {
        id: "hero1",
        title: "Hero 1",
        group: "hero",
        Component: Hero1,
        defaultContent: {
            badge: "> HERO_01",
            title: "Build your page in blocks",
            description: "Start with prebuilt sections and compose a complete landing page in minutes.",
            buttonLabel: "Start Building",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "hero2",
        title: "Hero 2",
        group: "hero",
        Component: Hero2,
        defaultContent: {
            badge: "> HERO_02",
            title: "Design with bold sections",
            description: "Mix and match creative hero variants to fit your page style.",
            buttonLabel: "Explore",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "hero3",
        title: "Hero 3",
        group: "hero",
        Component: Hero3,
        defaultContent: {
            badge: "> HERO_03",
            title: "Ship faster with flexible templates",
            description: "Use drag-and-drop options from the registry to assemble your page in minutes.",
            buttonLabel: "Build Now",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "features1",
        title: "Features 1",
        group: "features",
        Component: Features1,
        defaultContent: {
            badge: "> FEATURES_01",
            title: "Why this builder works",
            feature1Title: "Drag & Drop",
            feature1Desc: "Add sections to your page with one click.",
            feature2Title: "Reusable Blocks",
            feature2Desc: "Use the same section presets across projects.",
            feature3Title: "Live Preview",
            feature3Desc: "See the page flow update as you build.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "features2",
        title: "Features 2",
        group: "features",
        Component: Features2,
        defaultContent: {
            badge: "> FEATURES_02",
            title: "Choose the style you like",
            feature1Title: "Multiple Variants",
            feature1Desc: "Each section type includes several options to pick from.",
            feature2Title: "Instant Preview",
            feature2Desc: "Drop onto canvas and preview the result immediately.",
            feature3Title: "Inline Editing",
            feature3Desc: "Adjust text right on the section with edit mode enabled.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "features3",
        title: "Features 3",
        group: "features",
        Component: Features3,
        defaultContent: {
            badge: "> FEATURES_03",
            title: "Build pages your way",
            feature1Title: "Curated Blocks",
            feature1Desc: "All section options are available in one organized registry.",
            feature2Title: "Drag from Registry",
            feature2Desc: "Drag starts from options list and drops directly into preview canvas.",
            feature3Title: "Fast Iteration",
            feature3Desc: "Switch section options quickly as your design evolves.",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "feature1Title", label: "Feature 1 Title" },
            { key: "feature1Desc", label: "Feature 1 Description", multiline: true },
            { key: "feature2Title", label: "Feature 2 Title" },
            { key: "feature2Desc", label: "Feature 2 Description", multiline: true },
            { key: "feature3Title", label: "Feature 3 Title" },
            { key: "feature3Desc", label: "Feature 3 Description", multiline: true },
        ],
    },
    {
        id: "pricing1",
        title: "Pricing 1",
        group: "pricing",
        Component: Pricing1,
        defaultContent: {
            badge: "> PRICING_01",
            title: "Pick your plan",
            plan1Name: "Starter",
            plan1Price: "$0",
            plan1Desc: "Basic section presets and preview.",
            plan2Name: "Pro",
            plan2Price: "$19",
            plan2Desc: "More layouts and customization options.",
            plan3Name: "Studio",
            plan3Price: "$49",
            plan3Desc: "Advanced templates and team workflow.",
            buttonLabel: "Select",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "pricing2",
        title: "Pricing 2",
        group: "pricing",
        Component: Pricing2,
        defaultContent: {
            badge: "> PRICING_02",
            title: "Pick your plan",
            plan1Name: "Starter",
            plan1Price: "$0",
            plan1Desc: "Basic section presets and preview.",
            plan2Name: "Pro",
            plan2Price: "$19",
            plan2Desc: "More layouts and customization options.",
            plan3Name: "Studio",
            plan3Price: "$49",
            plan3Desc: "Advanced templates and team workflow.",
            buttonLabel: "Select",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "pricing3",
        title: "Pricing 3",
        group: "pricing",
        Component: Pricing3,
        defaultContent: {
            badge: "> PRICING_03",
            title: "Pick your plan",
            plan1Name: "Starter",
            plan1Price: "$0",
            plan1Desc: "Basic section presets and preview.",
            plan2Name: "Pro",
            plan2Price: "$19",
            plan2Desc: "More layouts and customization options.",
            plan3Name: "Studio",
            plan3Price: "$49",
            plan3Desc: "Advanced templates and team workflow.",
            buttonLabel: "Select",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "plan1Name", label: "Plan 1 Name" },
            { key: "plan1Price", label: "Plan 1 Price" },
            { key: "plan1Desc", label: "Plan 1 Description", multiline: true },
            { key: "plan2Name", label: "Plan 2 Name" },
            { key: "plan2Price", label: "Plan 2 Price" },
            { key: "plan2Desc", label: "Plan 2 Description", multiline: true },
            { key: "plan3Name", label: "Plan 3 Name" },
            { key: "plan3Price", label: "Plan 3 Price" },
            { key: "plan3Desc", label: "Plan 3 Description", multiline: true },
            { key: "buttonLabel", label: "Button Label" },
        ],
    },
    {
        id: "workpage1",
        title: "WorkPage 1",
        group: "work",
        Component: WorkPage1,
        defaultContent: {
            badge: "> WORKPAGE_01",
            title: "Template workflow",
            description:
                "This section shows what your current page build includes and what will be exported as a complete webpage template.",
            item1: "Hero + CTA layout",
            item2: "Feature grid with icons",
            item3: "Pricing cards with actions",
            item4: "Footer with quick links",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage2",
        title: "WorkPage 2",
        group: "work",
        Component: WorkPage2,
        defaultContent: {
            badge: "> WORKPAGE_02",
            title: "Template workflow",
            description:
                "This section shows what your current page build includes and what will be exported as a complete webpage template.",
            item1: "Hero + CTA layout",
            item2: "Feature grid with icons",
            item3: "Pricing cards with actions",
            item4: "Footer with quick links",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage3",
        title: "WorkPage 3",
        group: "work",
        Component: WorkPage3,
        defaultContent: {
            badge: "> WORKPAGE_03",
            title: "Template workflow",
            description:
                "This section shows what your current page build includes and what will be exported as a complete webpage template.",
            item1: "Hero + CTA layout",
            item2: "Feature grid with icons",
            item3: "Pricing cards with actions",
            item4: "Footer with quick links",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "workpage4",
        title: "WorkPage 4",
        group: "work",
        Component: WorkPage4,
        defaultContent: {
            badge: "> WORKPAGE_04",
            title: "Template workflow",
            description:
                "This section shows what your current page build includes and what will be exported as a complete webpage template.",
            item1: "Hero + CTA layout",
            item2: "Feature grid with icons",
            item3: "Pricing cards with actions",
            item4: "Footer with quick links",
        },
        fields: [
            { key: "badge", label: "Badge" },
            { key: "title", label: "Title" },
            { key: "description", label: "Description", multiline: true },
            { key: "item1", label: "Item 1" },
            { key: "item2", label: "Item 2" },
            { key: "item3", label: "Item 3" },
            { key: "item4", label: "Item 4" },
        ],
    },
    {
        id: "footer1",
        title: "Footer 1",
        group: "footer",
        Component: Footer1,
        defaultContent: {
            brand: "BLCKS",
            subtitle: "Template Builder Foundation",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            copyrightLine: "BLCKS. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
    {
        id: "footer2",
        title: "Footer 2",
        group: "footer",
        Component: Footer2,
        defaultContent: {
            brand: "BLCKS",
            subtitle: "Template Builder Foundation",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            copyrightLine: "BLCKS. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
    {
        id: "footer3",
        title: "Footer 3",
        group: "footer",
        Component: Footer3,
        defaultContent: {
            brand: "BLCKS",
            subtitle: "Template Builder Foundation",
            link1: "Home",
            link2: "Build",
            link3: "Pricing",
            link4: "Contact",
            copyrightLine: "BLCKS. All rights reserved.",
        },
        fields: [
            { key: "brand", label: "Brand" },
            { key: "subtitle", label: "Subtitle" },
            { key: "link1", label: "Link 1" },
            { key: "link2", label: "Link 2" },
            { key: "link3", label: "Link 3" },
            { key: "link4", label: "Link 4" },
            { key: "copyrightLine", label: "Copyright" },
        ],
    },
];

export default sectionRegistry;